export type Locale = 'en' | 'pt';

export const TRANSLATIONS: Record<string, Record<Locale, string>> = {
  'nav.home': { en: 'Home', pt: 'Início' },
  'nav.about': { en: 'About', pt: 'Sobre' },
  'nav.projects': { en: 'Projects', pt: 'Projetos' },
  'nav.experiences': { en: 'Experiences', pt: 'Experiências' },
  'nav.education': { en: 'Education', pt: 'Educação' },
  'nav.contact': { en: 'Contact me', pt: 'Contato' },
  'nav.resume': { en: 'Resume', pt: 'Currículo' },
  'nav.language': { en: 'Language', pt: 'Idioma' },
  'nav.download': { en: 'Download', pt: 'Baixar' },
  'nav.skills': { en: 'Skills', pt: 'Habilidades' },
  'nav.certifications': { en: 'Certifications', pt: 'Certificações' },
  'about.eyebrow': { en: 'Senior Software Engineer • Fullstack Developer • Tech Lead • Architect ', pt: 'Engenheiro de Software Sênior • Fullstack Developer • Tech Lead • Arquiteto' },
  'about.slide1.eyebrow': { en: 'Senior Software Engineer', pt: 'Engenheiro de Software Sênior' },
  'about.slide1.title':   { en: 'Angular · JavaScript | Java · Spring Boot', pt: 'Angular · JavaScript | Java · Spring Boot' },
  'about.slide2.eyebrow': { en: 'Tech Lead & Software Architect', pt: 'Tech Lead & Arquiteto de Software' },
  'about.slide2.title':   { en: 'Microservices · Cloud Native | AWS · Azure', pt: 'Microsserviços · Cloud Native | AWS · Azure' },
  'about.slide3.eyebrow': { en: 'Fullstack & Mobile Developer', pt: 'Desenvolvedor Fullstack & Mobile' },
  'about.slide3.title':   { en: 'Angular · Ionic | Java · PHP | REST APIs', pt: 'Angular · Ionic | Java · PHP | REST APIs' },
  'about.slide4.eyebrow': { en: 'Mentor & Community Builder', pt: 'Mentor & Construtor de Comunidade' },
  'about.slide4.title':   { en: '100+ Professionals Mentored | Career Reboot', pt: '100+ Profissionais Mentorados | Career Reboot' },
  'about.slide5.eyebrow': { en: 'AI & Agentic Systems Engineer', pt: 'Engenheiro de IA & Sistemas Agênticos' },
  'about.slide5.title':   { en: 'GitHub Copilot · LLM Agents | AI-Driven Dev', pt: 'GitHub Copilot · Agentes LLM | Dev Orientado a IA' },
  'about.beginning.title': { en: 'My Beginning', pt: 'Meu Início' },
  'about.beginning.text': { en: `While I was completing my studies, I was accepted into a university and began my career as a Computer Science instructor. In this role, I taught introductory programming courses to students in their early semesters.

This experience became my first real opportunity to understand the impact of mentoring junior developers, many of whom were taking their very first steps in software development. It challenged me not only to teach technical concepts, but also to guide, motivate, and build confidence in beginners.

Over the course of seven years, I developed a strong passion for helping others grow. One of my greatest learnings was how to inspire people to recognize how vast, exciting, and full of possibilities the IT field is—and to share the same enthusiasm I have for the world of software development.`, pt: `Enquanto ainda completava meus estudos, fui aceito em uma universidade e iniciei minha carreira como professor de Ciência da Computação. Nessa função, ministrei disciplinas introdutórias de programação para alunos nos primeiros semestres.

Essa experiência se tornou minha primeira oportunidade real de entender o impacto de mentorar desenvolvedores iniciantes, muitos dos quais davam seus primeiros passos no desenvolvimento de software. Foi um desafio que me exigiu não apenas ensinar conceitos técnicos, mas também orientar, motivar e construir a confiança dos alunos.

Ao longo de sete anos, desenvolvi uma forte paixão por ajudar outras pessoas a crescer. Um dos meus maiores aprendizados foi saber como inspirar as pessoas a reconhecerem o quão vasto, empolgante e cheio de possibilidades é o campo da TI — e compartilhar o mesmo entusiasmo que tenho pelo mundo do desenvolvimento de software.`},
  'about.background.title': { en: 'My Current Background', pt: 'Minha Situação Atual' },
  'about.background.text': { en: `Senior Software Engineer with 10+ years of experience in back-end development using Java and Spring Boot, and over 6 years of front-end experience with Angular.
Strong expertise in designing scalable microservices and microfrontend architectures, with hands-on experience in building high-performance user interfaces using RxJS, lazy loading strategies, and ag-Grid for real-time data rendering.
Solid foundation in software engineering best practices, including Clean Code, SOLID, DRY, and Domain-Driven Design (DDD). Experienced in cloud-based solutions on Azure and AWS, as well as CI/CD pipelines, DevOps practices, and application security.
Recognized as a technical reference, contributing to complex problem-solving, architectural decision-making, and cross-team collaboration. Passionate about automation, secure development, and leveraging Copilot-based agents to enhance testing, documentation, and overall team productivity.`, pt: `Engenheiro de Software Sênior com mais de 10 anos de experiência em desenvolvimento back-end usando Java e Spring Boot, e mais de 6 anos de experiência front-end com Angular.
Forte expertise em projetar arquiteturas escaláveis de microsserviços e microfrontends, com experiência prática na construção de interfaces de alto desempenho utilizando RxJS, estratégias de lazy loading e ag-Grid para renderização de dados em tempo real.
Base sólida em boas práticas de engenharia de software, incluindo Clean Code, SOLID, DRY e Domain-Driven Design (DDD). Experiente em soluções baseadas em nuvem no Azure e AWS, bem como em pipelines de CI/CD, práticas de DevOps e segurança de aplicações.
Reconhecido como referência técnica, contribuindo para resolução de problemas complexos, tomada de decisões arquiteturais e colaboração entre equipes. Apaixonado por automação, desenvolvimento seguro e pelo uso de agentes baseados em Copilot para aprimorar testes, documentação e a produtividade geral da equipe.` },
  'about.career.title': { en: 'My Career Path', pt: 'Minha Trajetória' },
  'about.career.text': { en: `In 2018, I decided to pursue entrepreneurship, focusing on ERP solutions for small businesses. During this period, I deepened my understanding of end-to-end software development, including requirements gathering, architectural decision-making, infrastructure cost management, production issue handling, and direct stakeholder engagement. These challenges significantly elevated my technical and business maturity.

In 2022, I joined Capgemini, where I became part of global, large-scale corporate projects. In this environment, I was able to validate and expand my experience by mentoring and training over 100 junior and mid-level professionals, including developers, QA engineers, and Scrum Masters.

Additionally, I founded the Career Reboot community, aimed at helping professionals transition into the IT field as QA engineers, Java developers, or Scrum Masters. To date, more than 60% of participants have successfully secured roles and are building successful careers in technology.`, pt: `Em 2018, decidi empreender, com foco em soluções ERP para pequenas empresas. Nesse período, aprofundei meu entendimento sobre o desenvolvimento de software de ponta a ponta, incluindo levantamento de requisitos, tomada de decisões arquiteturais, gestão de custos de infraestrutura, resolução de problemas em produção e relacionamento direto com stakeholders. Esses desafios elevaram significativamente minha maturidade técnica e de negócios.

Em 2022, ingressei na Capgemini, onde passei a fazer parte de projetos corporativos globais em larga escala. Nesse ambiente, pude validar e expandir minha experiência mentorando e capacitando mais de 100 profissionais júnior e pleno, incluindo desenvolvedores, engenheiros de QA e Scrum Masters.

Além disso, fundei a comunidade Career Reboot, voltada para ajudar profissionais a migrarem para a área de TI como engenheiros de QA, desenvolvedores Java ou Scrum Masters. Até o momento, mais de 60% dos participantes conseguiram seus primeiros empregos e estão construindo carreiras de sucesso na tecnologia.` },
  'about.future.title': { en: 'Where I Will Be in 1 Year', pt: 'Onde Estarei em 5 Anos' },
  'about.future.text': { en: `In one year, I see myself operating at the intersection of software architecture, engineering leadership, and AI-driven systems. My focus is on designing distributed platforms that are not only technically robust but also purposeful—products that respect users' time and deliver meaningful value.
I am actively strengthening my expertise in cloud-native architecture, with a particular focus on AWS Solutions Architecture, while deepening my knowledge of distributed systems using Java and Spring Boot, and advancing my front-end capabilities with Angular. I am also expanding my skills in event-driven architecture, enabling the design of scalable, decoupled, and resilient systems that can efficiently process real-time data and complex workflows.
Additionally, I am investing in infrastructure as code using Terraform to create scalable, reliable, and cost-efficient environments, and in observability practices to ensure system reliability through effective monitoring, logging, and tracing. These capabilities are essential for building and operating modern, production-ready platforms at scale.
At the same time, I am expanding into AI-powered tooling and intelligent agents, leveraging technologies such as GitHub Copilot to enhance engineering productivity, automation, and innovation.
Beyond technology, I am committed to evolving as a leader—developing the skills needed to build, mentor, and scale high-performing engineering teams. My goal is not only to build great software, but to shape the environments, architectures, and engineering cultures where great software consistently emerges.`, pt: `Em um ano, me vejo atuando na intersecção entre arquitetura de software, liderança de engenharia e sistemas orientados por IA. Meu foco está em projetar plataformas distribuídas que sejam não apenas tecnicamente robustas, mas também propositais — produtos que respeitam o tempo dos usuários e entregam valor real.
Estou fortalecendo ativamente minha expertise em arquitetura cloud-native, com foco especial em AWS Solutions Architecture, aprofundando meu conhecimento em sistemas distribuídos com Java e Spring Boot e avançando minhas capacidades front-end com Angular. Também estou expandindo minhas habilidades em arquitetura orientada a eventos, permitindo o design de sistemas escaláveis, desacoplados e resilientes, capazes de processar dados em tempo real e fluxos de trabalho complexos com eficiência.
Além disso, estou investindo em infraestrutura como código com Terraform para criar ambientes escaláveis, confiáveis e com boa relação custo-benefício, e em práticas de observabilidade para garantir a confiabilidade dos sistemas por meio de monitoramento, logging e tracing eficazes. Essas capacidades são essenciais para construir e operar plataformas modernas e prontas para produção em escala.
Ao mesmo tempo, estou expandindo para ferramentas com IA e agentes inteligentes, aproveitando tecnologias como o GitHub Copilot para aumentar a produtividade, a automação e a inovação em engenharia.
Além da tecnologia, estou comprometido em evoluir como líder — desenvolvendo as habilidades necessárias para construir, mentorar e escalar times de engenharia de alta performance. Meu objetivo não é apenas construir ótimos softwares, mas moldar os ambientes, as arquiteturas e as culturas de engenharia onde ótimos softwares emergem de forma consistente.` },
  'about.title': { en: 'Angular/Javascript | Java/Spring Boot | Ionic | AWS', pt: 'Angular/Javascript | Java/Spring Boot | Ionic | AWS' },

  'experiences.title': { en: 'Professional Experience', pt: 'Experiência Profissional' },
  'experiences.capgemini.title': { en: 'Capgemini', pt: 'Capgemini' },
  'experiences.capgemini.location': { en: 'Architect | Full-Stack (Angular/Java) | Apr 2022 (Present)', pt: 'Arquiteto | Full-Stack (Angular/Java) | Abr 2022 (Presente)' },
  'experiences.capgemini.role': { en: 'Architect · Full-Stack Engineer', pt: 'Arquiteto · Engenheiro Full-Stack' },
  'experiences.capgemini.date': { en: 'Apr 2022 — Present', pt: 'Abr 2022 — Presente' },
  'experiences.capgemini.summary': { en: 'Leading full-stack development and architectural decisions on an enterprise-scale Exchange Manager platform—driving 20% performance gains, 75% reduction in delivery lead time, and 40% increase in activated function points.', pt: 'Liderando o desenvolvimento full-stack e decisões arquiteturais em uma plataforma corporativa de Exchange Manager—alcançando 20% de ganho de performance, 75% de redução no lead time e 40% de aumento nos pontos de função ativados.' },
  'experiences.capgemini.line1': { en: 'Modernized and upgraded a large-scale Exchange Manager platform built on Angular 8+ and Java/Spring Boot—improving performance by 20% and optimizing JVM resource utilization.', pt: 'Modernizou e evoluiu uma plataforma corporativa de Exchange Manager desenvolvida em Angular 8+ e Java/Spring Boot, melhorando a performance em 20% e otimizando o uso de recursos da JVM.' },
  'experiences.capgemini.line2': { en: 'Worked with Hibernate/JPA, implementing entity mapping, relationships, pagination, and query optimization for relational databases.', pt: 'Trabalhou com Hibernate/JPA, realizando mapeamento de entidades, relacionamentos, paginação e otimização de consultas em bancos relacionais.' },
  'experiences.capgemini.line3': { en: 'Reduced feature delivery lead time by 75% and increased activated function points by 40% by improving CI/CD workflows, refining architecture boundaries, and removing bottlenecks in full-stack delivery pipelines.', pt: 'Reduziu o lead time de entrega de funcionalidades em 75% e aumentou em 40% os pontos de função ativados, por meio de melhorias em CI/CD, definição de limites arquiteturais e remoção de gargalos no full stack.' },
  'experiences.capgemini.line4': { en: 'Designed microfrontend, microservices, and event-driven architectures using Kafka, applying Domain-Driven Design, SOLID, DRY, Clean Code, Hexagonal Architecture, and layered patterns such as Facade, Singleton, and Builder.', pt: 'Projetou arquiteturas de microfrontend, microsserviços e sistemas orientados a eventos utilizando Kafka, aplicando Domain-Driven Design (DDD), Clean Code, SOLID, Arquitetura Hexagonal e padrões como Facade, Singleton e Builder.' },
  'experiences.capgemini.line5': { en: 'Applied cloud and container architectural concepts including Docker, API Gateway routing, distributed tracing, caching, and event-driven architecture, with exposure to event sourcing, Kubernetes, and Infrastructure-as-Code concepts (Terraform/ARM templates).', pt: 'Aplicou conceitos de arquitetura cloud e containers com Docker, API Gateway, tracing distribuído, cache, além de contato com Kubernetes e Infraestrutura como Código (Terraform/ARM).' },
  'experiences.capgemini.line6': { en: 'Implemented secure authentication and authorization across distributed services using JWT/OAuth2, OWASP-aligned secure coding practices, and API hardening strategies.', pt: 'Implementou autenticação e autorização seguras com JWT/OAuth2, seguindo práticas de segurança alinhadas ao OWASP e hardening de APIs.' },
  'experiences.capgemini.line7': { en: 'Supported production environments with Docker and Kubernetes, handling containerization, deployment configurations, and basic cluster operations.', pt: 'Atuou em ambientes produtivos com Docker e Kubernetes, realizando containerização, configuração de deploys e operações básicas de cluster.' },
  'experiences.capgemini.line8': { en: 'Managed application artifacts using Nexus Repository, handling versioning, dependency management, and release promotion.', pt: 'Gerenciou artefatos de aplicações usando Nexus Repository, cuidando de versionamento, dependências e promoção de releases.' },
  'experiences.capgemini.line9': { en: 'Developed real-time UI experiences using RxJS, reactive state management, and virtual scrolling to handle large data sets with high performance and low memory footprint.', pt: 'Desenvolveu interfaces em tempo real com RxJS, gerenciamento reativo de estado e virtual scrolling, garantindo alto desempenho e baixo consumo de memória.' },
  'experiences.capgemini.line10': { en: 'Built and maintained Angular applications integrated with Java/Spring Boot reactive REST APIs, distributed API Gateway patterns, and cloud-native components in Microsoft Azure, supported by GitHub Actions CI/CD and containerized deployments.', pt: 'Construiu e manteve aplicações Angular integradas a APIs REST reativas em Java/Spring Boot, utilizando padrões de API Gateway e serviços cloud no Microsoft Azure, com GitHub Actions para CI/CD.' },
  'experiences.capgemini.line11': { en: 'Led development squads in Agile/Scrum environments, coordinating developers and QA engineers, refining Jira/Confluence documentation, performing technical reviews, and supporting continuous delivery.', pt: 'Liderou squads em ambientes Ágeis (Scrum), coordenando desenvolvedores e QA, refinando histórias no Jira/Confluence, realizando revisões técnicas e apoiando a entrega contínua.' },
  'experiences.capgemini.line12': { en: 'Maintained and optimized legacy J2EE SOA systems using JavaFX, EJB on WebSphere 8 and Apache 6+, ensuring compliance and quality through Fortify/SonarQube analysis and BDD practices.', pt: 'Manteve e evoluiu sistemas legados J2EE utilizando EJB, WebSphere 8 e Apache, garantindo qualidade por meio de Fortify, SonarQube e práticas de BDD.' },
  'experiences.silva.title': { en: 'Silva and Queiroz Technology Information Services LTDA', pt: 'Silva and Queiroz Technology Information Services LTDA' },
  'experiences.silva.location': { en: 'FullStack Engineer (Angular/PHP) | Apr 2018 – 2022', pt: 'FullStack Engineer (Angular/PHP) | Abr 2018 – 2022' },
  'experiences.silva.role': { en: 'Full-Stack Engineer', pt: 'Engenheiro Full-Stack' },
  'experiences.silva.date': { en: 'Apr 2018 — 2022', pt: 'Abr 2018 — 2022' },
  'experiences.silva.summary': { en: 'Built progressive web applications using Ionic/Angular and PHP/Laravel backend services, delivering scalable multi-platform solutions with AWS and GCP cloud integrations.', pt: 'Construiu Progressive Web Applications com Ionic/Angular e back-end em PHP/Laravel, entregando soluções multiplataforma escaláveis com integrações AWS e GCP.' },
  'experiences.silva.line1': { en: 'Created progressive web applications using Ionic (v5/v6), Angular 14+, RxJS, Capacitor, and Materialize.', pt: 'Desenvolveu Progressive Web Applications (PWA) utilizando Ionic (v5/v6), Angular 14+, RxJS, Capacitor e Materialize.' },
  'experiences.silva.line2': { en: 'Implemented backend microservices built in Laravel 9, PHP 8, and MySQL.', pt: 'Implementou integrações com microsserviços back-end desenvolvidos em Laravel 9, PHP 8 e MySQL.' },
  'experiences.silva.line3': { en: 'Developed and maintained applications using relational databases such as MySQL/MariaDB, with adaptability to PostgreSQL, SQL Server, and Oracle environments.', pt: 'Desenvolveu e manteve aplicações utilizando bancos relacionais (MySQL/MariaDB), com facilidade de adaptação para PostgreSQL, SQL Server e Oracle.' },
  'experiences.silva.line4': { en: 'Utilized AWS cloud services (EC2, S3, IAM, CloudFront, ECS and RDS) to deploy and operate scalable backend applications.', pt: 'Utilizou serviços da AWS (EC2, S3, IAM, CloudFront, ECS e RDS) para deploy e operação de aplicações escaláveis.' },
  'experiences.silva.line5': { en: 'Delivered robust solutions supported by test automation with Jasmine and Robot Framework.', pt: 'Entregou soluções robustas apoiadas por testes automatizados com Jasmine e Robot Framework.' },
  'experiences.silva.line6': { en: 'Optimized Angular applications for speed and scalability by implementing lazy loading, change detection strategies, ag-Grid, and advanced caching techniques.', pt: 'Otimizou aplicações Angular aplicando lazy loading, estratégias de change detection, uso de ag-Grid e técnicas avançadas de cache.' },
  'experiences.silva.line7': { en: 'Configured and managed deployments using cPanel.', pt: 'Realizou configuração e gerenciamento de deploys em cPanel.' },
  'experiences.silva.line8': { en: 'Integrated GCP services (Firebase push notifications, authentication and identity platform) with Ionic/Angular applications.', pt: 'Integrou serviços do Google Cloud Platform, como Firebase (push notifications, autenticação e identidade), a aplicações Ionic/Angular.' },
  'experiences.professor.title': { en: 'Federal University of Recôncavo da Bahia', pt: 'Universidade Federal do Recôncavo da Bahia' },
  'experiences.professor.location': { en: 'Professor Engineer (Java) | Mar 2019 – Jul 2020', pt: 'Professor Engenheiro (Java) | Mar 2019 – Jul 2020' },
  'experiences.professor.role': { en: 'Engineer Professor', pt: 'Professor Engenheiro' },
  'experiences.professor.date': { en: 'Mar 2019 — Jul 2020', pt: 'Mar 2019 — Jul 2020' },
  'experiences.professor.summary': { en: 'Taught introductory programming concepts using Java, Python, Flask, and C++. Helped students improve their problem analysis and logical reasoning skills. Main Technologies: Java, JavaScript, Python, MySQL, Oracle.', pt: 'Ministrou conceitos introdutórios de programação com Java, Python, Flask e C++. Auxiliou alunos a aprimorar análise de problemas e raciocínio lógico. Principais tecnologias: Java, JavaScript, Python, MySQL, Oracle.' },
  'experiences.professor.line1': { en: 'Taught introductory and intermediate programming concepts using Java, Python, Flask, and C++, emphasizing clean code, software design principles, and problem-solving skills.', pt: 'Ministrou disciplinas de programação básica e intermediária com Java, Python, Flask e C++, enfatizando Clean Code, design de software e resolução de problemas.' },
  'experiences.professor.line2': { en: 'Guided students through requirements analysis, system design, and business communication, simulating real-world software development workflows and stakeholder interactions.', pt: 'Orientou alunos em levantamento de requisitos, desenho de sistemas e comunicação com stakeholders, simulando ambientes reais de desenvolvimento de software.' },
  'experiences.professor.line3': { en: 'Delivered structured lessons to 500+ students, strengthening analytical thinking, logical reasoning, and software architecture fundamentals through hands-on projects.', pt: 'Ministrou aulas estruturadas para mais de 500 alunos, fortalecendo raciocínio lógico, análise de problemas e fundamentos de arquitetura de software.' },
  'experiences.professor.line4': { en: 'Designed and supervised practical e-commerce and POS projects using hybrid applications and distributed architectures.', pt: 'Projetou e supervisionou projetos práticos de sistemas de e-commerce e PDV (Frente de Caixa), utilizando aplicações híbridas e arquiteturas distribuídas.' },
  'experiences.professor.line5': { en: 'Integrated e-NFC, receipt printers, barcode and QR code scanners, and payment machines into student projects.', pt: 'Conduziu integrações com e-NFC, impressoras fiscais, leitores de código de barras, QR Code e máquinas de pagamento.' },
  'experiences.professor.line6': { en: 'Created exercises bridging technical implementation and business needs, ensuring alignment between software solutions, operational constraints, and customer experience.', pt: 'Criou atividades práticas conectando implementação técnica às necessidades do negócio e da operação.' },
  'experiences.secretary.title': { en: 'Secretary of Education, Bahia, BR', pt: 'Secretaria de Educação, Bahia, BR' },
  'experiences.secretary.role': { en: 'Engineer Professor', pt: 'Professor Engenheiro' },
  'experiences.secretary.date': { en: 'Dec 2018 — May 2022', pt: 'Dez 2018 — Mai 2022' },
  'experiences.secretary.summary': { en: 'Taught introductory programming using Java, Python, and C++. Helped students improve their problem analysis and computational thinking skills. Main Technologies: Java, JavaScript, Python, MySQL, Oracle.', pt: 'Ministrou programação introdutória com Java, Python e C++. Auxiliou alunos a aprimorar análise de problemas e pensamento computacional. Principais tecnologias: Java, JavaScript, Python, MySQL, Oracle.' },
  'experiences.professor2.title': { en: 'Federal University of Recôncavo da Bahia', pt: 'Universidade Federal do Recôncavo da Bahia' },
  'experiences.professor2.role': { en: 'Engineer Professor', pt: 'Professor Engenheiro' },
  'experiences.professor2.date': { en: 'Mar 2015 — Mar 2017', pt: 'Mar 2015 — Mar 2017' },
  'experiences.professor2.summary': { en: 'Taught introductory programming using Java, Python, and C++. Helped students improve their problem analysis and computational thinking skills. Main Technologies: Java, Python, MySQL, Oracle.', pt: 'Ministrou programação introdutória com Java, Python e C++. Auxiliou alunos a aprimorar análise de problemas e pensamento computacional. Principais tecnologias: Java, Python, MySQL, Oracle.' },
  'projects.title': { en: 'Key Projects', pt: 'Projetos Principais' },
  'projects.item1': { en: 'Exchange Manager Platform - Modernized a large-scale platform with Angular and Java/Spring Boot, improving performance by 20%.', pt: 'Plataforma Exchange Manager - Modernizei uma plataforma em larga escala com Angular e Java/Spring Boot, melhorando a performance em 20%.' },
  'projects.item2': { en: 'Progressive Web Applications - Built PWAs using Ionic, Angular, and backend microservices with Laravel and MySQL.', pt: 'Aplicações Web Progressivas - Construí PWAs usando Ionic, Angular e microsserviços backend com Laravel e MySQL.' },
  'projects.item3': { en: 'E-commerce Systems - Designed and supervised hybrid app projects integrated with payment machines and scanners.', pt: 'Sistemas de E-commerce - Projetei e supervisei projetos de apps híbridos integrados com máquinas de pagamento e leitores.' },
  'projects.item4': { en: 'IoT Framework - Master’s research on reliable IoT data sources using blockchain and ML.', pt: 'Framework IoT - Pesquisa de mestrado sobre fontes de dados IoT confiáveis usando blockchain e ML.' },
  'projects.li_1': { en: 'Exchange Manager Platform', pt: 'Plataforma Exchange Manager' },
  'projects.li_1_desc': { en: 'Modernized a large-scale platform with Angular and Java/Spring Boot, improving performance by 20%.', pt: 'Modernizei uma plataforma em larga escala com Angular e Java/Spring Boot, melhorando a performance em 20%.' },
  'projects.li_2': { en: 'Progressive Web Applications', pt: 'Aplicações Web Progressivas' },
  'projects.li_2_desc': { en: 'Built PWAs using Ionic, Angular, and backend microservices with Laravel and MySQL.', pt: 'Construí PWAs usando Ionic, Angular e microsserviços backend com Laravel e MySQL.' },
  'projects.li_3': { en: 'E-commerce Systems', pt: 'Sistemas de E-commerce' },
  'projects.li_3_desc': { en: 'Designed and supervised hybrid app projects integrated with payment machines and scanners.', pt: 'Projetei e supervisei projetos de apps híbridos integrados com máquinas de pagamento e leitores.' },
  'projects.li_4': { en: 'IoT Framework', pt: 'Framework IoT' },
  'projects.li_4_desc': { en: 'Master’s research on reliable IoT data sources using blockchain and ML.', pt: 'Pesquisa de mestrado sobre fontes de dados IoT confiáveis usando blockchain e ML.' },
  'projects.li_5': { en: 'ChatBot Applications', pt: 'Aplicações ChatBot' },
  'projects.li_5_desc': { en: 'Developed chatBot applications using Ionic and Laravel, integrating with various APIs and services.', pt: 'Desenvolvi aplicações ChatBot usando Ionic e Laravel, integrando com várias APIs e serviços.' },
  'projects.li_6': { en: 'Personal Portfolio', pt: 'Portfólio Pessoal' },
  'projects.li_6_desc': { en: 'This portfolio — built with Angular 21, Angular Material, SCSS, and i18n support. Features a responsive bento-grid layout, scroll-reveal animations, and a mobile-first design.', pt: 'Este portfólio — desenvolvido com Angular 21, Angular Material, SCSS e suporte a i18n. Inclui layout bento-grid responsivo, animações de scroll-reveal e design mobile-first.' },
  'projects.li_7': { en: 'Invest API', pt: 'API de Investimentos' },
  'projects.li_7_desc': { en: 'Developed an investment API using modern backend technologies, ensuring secure and efficient data handling.', pt: 'Desenvolvi uma API de investimentos usando tecnologias backend modernas, garantindo manipulação de dados segura e eficiente.' },
  'education.title': { en: 'Education', pt: 'Educação' },
  'education.li_1': { en: 'UNIPDS Educação — Postgraduate — Java Elite (Nov 2025) | Advanced modern Java development and architecture.', pt: 'UNIPDS Educação — Pós-graduação — Java Elite (Nov 2025) | Desenvolvimento moderno de Java e arquitetura avançada.' },
  'education.li_2': { en: 'Federal University of Bahia — Master in Computer Science (Jul 2021 – Nov 2024) | IoT, blockchain, smart contracts, and ML for data validation.', pt: 'Universidade Federal da Bahia — Mestrado em Ciência da Computação (Jul 2021 – Nov 2024) | IoT, blockchain, smart contracts e ML para validação de dados.' },
  'education.li_3': { en: 'Information and Management Technology Institute  (IGTI) — MBA in Cyber Security (Mar 2018 – Feb 2019) | Security strategies for web application resilience.', pt: 'Instituto de Tecnologia da Informação e Gestão (IGTI) — MBA em Cibersegurança (Mar 2018 – Fev 2019) | Estratégias de segurança para resiliência de aplicações web.' },
  'education.li_4': { en: 'Federal University of Recôncavo da Bahia — Bachelor in Computer Engineering (Feb 2013 – Aug 2018) | Stress detection system using ECG and ML.', pt: 'Universidade Federal do Recôncavo da Bahia — Bacharelado em Engenharia de Computação (Fev 2013 – Ago 2018) | Sistema de detecção de estresse usando ECG e ML.' },
  'resume.certifications': { en: 'Certifications', pt: 'Certificações' },
  'resume.languages': { en: 'Languages', pt: 'Idiomas' },
  'resume.cert1': { en: 'Java Certified Foundations - Associate - 1Z0-811', pt: 'Java Certified Foundations - Associate - 1Z0-811' },
  'resume.cert2': { en: 'Microsoft Azure Fundamentals — AZ-900 (2023)', pt: 'Microsoft Azure Fundamentals — AZ-900 (2023)' },
  'resume.cert3': { en: 'Aspiring Architecture — L0 (2025)', pt: 'Aspiring Architecture — L0 (2025)' },
  'resume.lang1': { en: 'Portuguese: Native', pt: 'Português: Nativo' },
  'resume.lang2': { en: 'English: B2', pt: 'Inglês: B2' },
  'resume.lang3': { en: 'Spanish: A1', pt: 'Espanhol: A1' },
  'stacks.title': { en: 'Skills Timeline', pt: 'Linha do Tempo de Skills' },
  'stacks.frontend': { en: 'Angular (6 yrs), TypeScript (6 yrs), JavaScript (7 yrs), RxJS (5 yrs), HTML (10 yrs), SCSS (10 yrs), Chart.js (5 yrs), Ionic (5 yrs), Figma (2 yrs)', pt: 'Angular (6 anos), TypeScript (6 anos), JavaScript (7 anos), RxJS (5 anos), HTML (10 anos), SCSS (10 anos), Chart.js (5 anos), Ionic (5 anos), Figma (2 anos)' },
  'stacks.backend': { en: 'Java (10 yrs), Spring Boot (5 yrs), RESTful APIs (5 yrs), JSON (5 yrs), MariaDB/MySQL (10 yrs), MongoDB (1 yr), Kafka (1 yr)', pt: 'Java (10 anos), Spring Boot (5 anos), RESTful APIs (5 anos), JSON (5 anos), MariaDB/MySQL (10 anos), MongoDB (1 ano), Kafka (1 ano)' },
  'stacks.devops': { en: 'Azure (2 yrs), GCP (4 yrs), AWS (1 yr), Docker (3 yrs), Kubernetes (1 yr), GitHub Actions (3 yrs), cPanel (10 yrs)', pt: 'Azure (2 anos), GCP (4 anos), AWS (1 ano), Docker (3 anos), Kubernetes (1 ano), GitHub Actions (3 anos), cPanel (10 anos)' },
  'stacks.testing': { en: 'Unit Tests (JUnit, Jest, Jasmine, Mockito), Manual & Automation E2E (Cucumber), Gherkin, Postman', pt: 'Testes Unitários (JUnit, Jest, Jasmine, Mockito), E2E Manual & Automação (Cucumber), Gherkin, Postman' },
  'stacks.tools': { en: 'Jira, Confluence, GitHub, GitLab, Bitbucket, Figma, Copilot Agent Creation, Documentation', pt: 'Jira, Confluence, GitHub, GitLab, Bitbucket, Figma, Criação de Agentes Copilot, Documentação' },
  'contact.title': { en: 'Contact Me', pt: 'Fale Comigo' },
};
